### ISSUE TITLE
Find alternative to popup

### ISSUE THREAD

**Issue by wish13yt** [Freakybob-Team/Freakybob.site#17]
The popup is starting to make my PC unable to locally test new builds. (lag)
# Possible Solutions
- Make/use a button (like the mute button)
- Don't play music until the webpage has been interacted with

**Comment by 5quirre1** [comment]
Alr, So the popup is meant to activate the music since the bug did not allow it to play. I think this is a great idea plus we know more code so we could probably fix it. The popup can be taken away but we probably do the thing when the music plays only when you interact with the screen. 

Tho let's figure it out once I finish everything plz ^^

**Comment by wish13yt** [comment]
# Solution found
const ks = new Audio('https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3')
let userinteraction = 0
document.addEventListener('click',()=>{
 if(userinteraction) return;
 userinteraction++;
 ks.play()
})
